name: midigen
description: A CLI for generating random midi chord sequences, made to inspire creativity.
version: 0.0.1
homepage: https://github.com/jeroen-meijer/midigen
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  args: ^2.3.0
  cli_dialog: ^0.5.0
  equatable: ^2.0.3
  indent: ^2.0.0
  io: ^1.0.3
  meta: ^1.7.0
  path: ^1.8.0
  tekartik_midi:
    git:
      url: git://github.com/tekartik/midi.dart.git
      ref: 008ac5210a0378155840ba81aa415e88623e56cc
  universal_io: ^2.0.4
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.2
  build_verify: ^2.0.0
  build_version: ^2.1.0
  coverage: ^1.0.3
  mocktail: ^0.1.4
  test: ^1.18.0
  very_good_analysis: ^2.3.0

executables:
  midigen: midigen
